#!/usr/bin/env bash

# byzanz is used to record gif
# xrectsel is used to get coordinates where to record

#HOW TO USE

#   run gif_area
#   select area by dragging a rectangle with the mouse
#   records gif of the area for 10 seconds
#   find the done gif in your ~/Pictures/screenshots/

# you can pass arguments

# gif_area 30
# records for 30 seconds

# gif_area 19 testing
# records for 19 secs, file will be called testing.gif

delay=3
path="$HOME/Pictures/screenshots/gif_$(date +"%s")"

beep() {
    play ~/media/shutter.ogg
}

if [ $# -gt 1 ]; then
    dur="=$1"
    path="$HOME/Pictures/screenshots/"$2
elif [ $# -gt 0 ]; then
    dur="$1"
else
    dur="10"
fi

# xrectsel from https://github.com/lolilolicon/xrectsel
# get desired rectangle's dimensions and coordinates using xrectsel
arguments=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

for (( i=$delay; i>0; --i )) ; do
    echo $i
    sleep 1
done

beep
byzanz-record --verbose --delay=0 ${arguments} --duration=$dur $path.gif
beep
