#!/usr/bin/env bash

#takes area screenshot, compares jpg/png
#keeps jpg only if its considerably smaller than png

#scrot to take area screenshots
#sox to play audio file
#imagemagick to convert pictures

type scrot convert play > /dev/null || exit

shot=$HOME/Pictures/screenshots/$(date +%s)

scrot -s "$shot.png" || exit

play $HOME/media/shutter.ogg

convert "$shot.png" "$shot.jpg" || exit

read -r pngsize _ < <(wc -c "$shot.png")
read -r jpgsize _ < <(wc -c "$shot.jpg")

if (( pngsize < 3 * jpgsize )); then
    rm "$shot.jpg"
else
    rm "$shot.png"
fi

